services:
  docuseal:
    build:
      context: ./
      dockerfile: Dockerfile
    image: docuseal-local:latest
    ports:
      - "8081:3000"
    volumes:
      - docuseal_data:/data
    environment:
      # DATABASE_URL: postgresql://therapypms_forms_user:6yq0AlreBFRFj8jd@40.160.16.121:5432/therapypms_forms_doc
      DATABASE_URL: postgresql://postgres:postgres@host.docker.internal:5432/therapypms_form
      SECRET_KEY_BASE: d1241ec234d59b208f90bd2390180ad8cb5c814509092b61e97c75107aa9d591c0a34f6a27dc785b36ea0af3e7a69a65fabb2e265b5e575936fb05363a2565ff
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # restart: unless-stopped
volumes:
  docuseal_data: